/**
 * Regenerate docs/MODULE-MAP.md — the function → file ownership index.
 *
 *   node scripts/module-map.mjs > docs/MODULE-MAP.md     (npm run module-map)
 *   node scripts/module-map.mjs --check                  fail if the file drifted
 *
 * One row per source file: its @tags header (when present) and its exported
 * symbols. Line numbers are deliberately absent — grep the symbol, not a
 * rotting number. Rule of the map: a name lives in exactly one row; a caller
 * in another file imports it.
 */
import { readdirSync, readFileSync, existsSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const check = process.argv.includes("--check");

const DIRS = [
  { dir: "renderer", title: "renderer core (state, geometry, 3D)", excludeDirs: ["gen", "interact", "panel", "bench", "modules"] },
  { dir: "renderer/interact", title: "interact/* — pointer/key modes behind the interact.js shell" },
  { dir: "renderer/panel", title: "panel/* — right-panel editors behind the panel.js shell" },
  { dir: "renderer/bench", title: "bench/* — generator bench window behind the bench/bench.js shell" },
  { dir: "renderer/modules", title: "modules/* — pure helper domains behind the modules.js registry" },
  { dir: "generators", title: "generators/<module> — parametric sources (TS)", only: /generator\.ts$/ },
  { dir: "generators/_lib", title: "generators/_lib — shared generator library", only: /\.ts$/, skip: /\.test\.ts$/ },
];

const EXPORT_RE = /^export\s+(?:async\s+)?(?:function|const|let|class)\s+([A-Za-z0-9_$]+)/gm;
const REEXPORT_RE = /^export\s*\{([^}]+)\}\s*from\s*["']([^"']+)["']/gm;
const TAG_RE = /^\/\/\s*@(\w+)\s+(.+)$/gm;

const files = [];
const walk = (dir, only, skip, excludeDirs) => {
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    const r = relative(root, p).replace(/\\/g, "/");
    if (e.isDirectory()) { if (excludeDirs?.includes(e.name)) continue; walk(p, only, skip, excludeDirs); continue; }
    if (!/\.(js|ts|mjs)$/.test(e.name)) continue;
    if (/\.test\.[jt]s$/.test(e.name)) continue;
    if (only && !only.test(e.name)) continue;
    if (skip && skip.test(r.slice(r.indexOf("/") + 1))) continue;
    files.push(p);
  }
};

let out = `# Module map\n\n` +
  `Generated by \`npm run module-map\` — do not hand-edit. Regenerate after ` +
  `moving or renaming functions. The grep-first reading rules live in ` +
  `\`.cursor/rules/cab-lab-index.mdc\`.\n`;

for (const { dir, title, only, skip, excludeDirs } of DIRS) {
  const abs = join(root, dir);
  if (!existsSync(abs)) continue;
  files.length = 0;
  walk(abs, only, skip, excludeDirs);
  const key = (p) => relative(root, p).replace(/\\/g, "/");
  files.sort((a, b) => (key(a) < key(b) ? -1 : key(a) > key(b) ? 1 : 0));
  out += `\n## ${title}\n\n| file | tags | exports |\n|---|---|---|\n`;
  for (const f of files) {
    const text = readFileSync(f, "utf8");
    const exports = [...text.matchAll(EXPORT_RE)].map((m) => m[1]);
    const reexports = [...text.matchAll(REEXPORT_RE)]
      .flatMap((m) => m[1].split(",").map((s) => s.trim().split(/\s+as\s+/).pop()))
      .filter(Boolean);
    const tags = [...text.matchAll(TAG_RE)].map((m) => `${m[1]}: ${m[2].trim()}`).join(" · ");
    const names = [...new Set([...exports, ...reexports])].sort();
    out += `| ${relative(root, f).replace(/\\/g, "/")} | ${tags || "—"} | ${names.join(", ") || "—"} |\n`;
  }
}

if (check) {
  const existing = readFileSync(join(root, "docs/MODULE-MAP.md"), "utf8").replace(/\r\n/g, "\n");
  if (existing !== out) {
    const a = existing.split("\n"), b = out.split("\n");
    const i = a.findIndex((l, k) => l !== b[k]);
    console.error(`MODULE-MAP.md is stale — run npm run module-map`);
    console.error(`first diff at line ${i + 1}:`);
    console.error(`  file:      ${a[i] ?? "(end)"}`);
    console.error(`  generated: ${b[i] ?? "(end)"}`);
    process.exit(1);
  }
  console.log("MODULE-MAP.md up to date");
} else {
  process.stdout.write(out);
}
